---
- name: Install wartest environment
  hosts: all
  become: yes
  become_user: root
  vars:
    docker_image: "{{ image | default('registry.gitlab.com/cba2405234/presentation-jenkins/wartest:version-16') }}"

  tasks:

    - name: Gather facts
      ansible.builtin.setup:

    - name: Ensure python3-pip is installed
      ansible.builtin.apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install dependencies for Docker
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add Docker repository for Ubuntu Jammy
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
        filename: docker

    - name: Install Docker
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Ensure Docker service is started and enabled
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add Jenkins user to docker group
      ansible.builtin.user:
        name: jenkins
        groups: docker
        append: yes

    - name: Install docker Python module
      ansible.builtin.pip:
        name: docker
        executable: pip3

    - name: Wait for Docker socket to be available
      ansible.builtin.wait_for:
        path: /var/run/docker.sock
        state: present
        timeout: 30

    - name: Pull docker image
      community.docker.docker_image:
        name: "{{ docker_image }}"
        source: pull
